# Generated by Django 2.1.4 on 2019-01-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Language', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
    ]
